---
# Repository configuration for wetransform managed repositories

# Reference presets that should apply to this repository
presets:
  - reusable-workflows
  - renovate-config
  - workflows-default
