on:
  workflow_call:
    inputs:
      gradle-tasks:
        description: Tasks to run
        required: true
        type: string
      java-version:
        description: Java version to use for build
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #
      # Build, test and create Docker image
      #

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and test with Gradle
        env:
          ORG_GRADLE_PROJECT_wetfArtifactoryUser: ${{ secrets.WETF_ARTIFACTORY_USER }}
          ORG_GRADLE_PROJECT_wetfArtifactoryPassword: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
        run: ./gradlew dependencies --write-locks ${{ inputs.gradle-tasks }}

      #
      # Security scans
      #

        # https://github.com/aquasecurity/trivy-action
      - name: Scan file system for critical vulnerabilities
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          # skip-dirs: '.gradle,'
          format: 'template'
          template: '@/contrib/junit.tpl'
          output: 'build/test-results/trivy.xml' # added to unit test report
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: CRITICAL # 'CRITICAL,HIGH'

      - name: Create vulnerability report as HTML
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy.html'
      - name: Upload vulnerability report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Vulnerability report (HTML)
          path: trivy.html
          retention-days: 30

      - name: Download vulnerability summary template
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          curl -H "Authorization: token ${TOKEN}" -o summary.tpl https://raw.githubusercontent.com/wetransform/gha-workflows/master/trivy/summary.tpl
      - name: Create summary on vulnerabilities
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          format: 'template'
          template: '@summary.tpl'
          output: 'trivy.md'
      - name: Add to job summary
        run: |
          cat trivy.md >> $GITHUB_STEP_SUMMARY

      #
      # Report on unit tests and critical vulnerabilities
      #

        # https://github.com/marketplace/actions/junit-report-action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'build/test-results/**.xml'
          require_tests: true

          # Workaround for check that is additionally created being associated
          # to the wrong workflow/run. Instead not additional check is created.
          # See https://github.com/mikepenz/action-junit-report/issues/40
          annotate_only: true
          detailed_summary: true
          fail_on_failure: true # in case of critical security vulnerabilities
