on:
  workflow_call:
    inputs:
      java-version:
        description: Java version to use for build
        required: true
        type: string
    secrets:
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:
      SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  publish:
    uses: ./.github/workflows/gradle-library.yml
    with:
      gradle-tasks: 'clean check publishAllPublicationsToMavenRepository'
      java-version: ${{ inputs.java-version }}
    secrets: inherit
