on:
  workflow_call:
    inputs:
      commmand:
        description: Custom command to run
        default: ''
        required: false
        type: string
      java-version:
        description: Java version to use for build
        required: true
        type: string
      image-tag:
        description: Image tag to scan after build
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      DOCKER_HUB_EMAIL:
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:
      # SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  check:
    uses: ./.github/workflows/play-service.yml
    with:
      command: ${{ inputs.command != '' && inputs.command || './sbt clean update test docker:publishLocal' }}
      java-version: ${{ inputs.java-version }}
      image-tag: ${{ inputs.image-tag }}
      notify-failure: false
      push-image: false
    secrets: inherit
