on:
  workflow_call:
    inputs:
      images:
        description: Image tag to scan (Json array)
        required: true
        type: string
    secrets:
      # GH_PAT:
      #   required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_EMAIL:

jobs:
  scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJson(inputs.images) }}

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Vulnerability scan
        uses: wetransform/gha-trivy@master
        with:
          image-ref: ${{ matrix.image }}
          create-test-report: true
          report-tag: ${{ matrix.image }}
          report-retention-days: 30
